name: How can we improve our extensibility?
description: How can we improve our extensibility?
title: "[reccomendation]: "
labels: ["feature-requst", "integration"]
projects: ["issue-form-test", "issue-form-test"]
assignees:
  - Christa_Brehm
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this recommendation!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
 
